"""Initial schema, btree_gist and the no_double_booking exclusion constraint.

This migration is the whole of spec section 11 plus the layer 3 guarantee from
section 7. The EXCLUDE constraint is written as raw SQL because Alembic cannot
autogenerate it, and it is version-controlled here rather than applied by hand so
that every environment gets it and no environment can quietly lose it.

Booking, attendee, notification and audit ids are UUIDs generated by the
application with uuid4. Rooms keep their slug id and departments and users keep
integer ids: neither is ever exposed in a link.

Revision ID: 0001
Revises:
Create Date: 2026-08-29
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# PostgreSQL has no CREATE TYPE IF NOT EXISTS, so each enum is guarded. This
# keeps the migration re-runnable against a database where a previous attempt
# failed partway through.
def _create_enum(name: str, values: Sequence[str]) -> None:
    labels = ", ".join(f"'{value}'" for value in values)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{name}') THEN
                CREATE TYPE {name} AS ENUM ({labels});
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    # ------------------------------------------------------------------ extension
    # btree_gist supplies the "=" operator class that lets a GiST exclusion
    # constraint mix a scalar (room_id) with a range. Without it the constraint
    # in section 7 cannot be created at all.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")

    # ---------------------------------------------------------------------- enums
    _create_enum("user_role", ("EMPLOYEE", "RECEPTION", "ADMIN"))
    _create_enum("booking_status", ("CONFIRMED", "CANCELLED", "NO_SHOW"))
    _create_enum("attendee_response", ("PENDING", "ACCEPTED", "DECLINED"))
    _create_enum("notification_event", ("BOOKED", "CHANGED", "CANCELLED"))
    _create_enum("notification_status", ("QUEUED", "SENT", "FAILED"))

    user_role = postgresql.ENUM(
        "EMPLOYEE", "RECEPTION", "ADMIN", name="user_role", create_type=False
    )
    booking_status = postgresql.ENUM(
        "CONFIRMED", "CANCELLED", "NO_SHOW", name="booking_status", create_type=False
    )
    attendee_response = postgresql.ENUM(
        "PENDING",
        "ACCEPTED",
        "DECLINED",
        name="attendee_response",
        create_type=False,
    )
    notification_event = postgresql.ENUM(
        "BOOKED", "CHANGED", "CANCELLED", name="notification_event", create_type=False
    )
    notification_status = postgresql.ENUM(
        "QUEUED", "SENT", "FAILED", name="notification_status", create_type=False
    )

    # --------------------------------------------------------------- departments
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("name", name=op.f("uq_departments_name")),
    )

    # --------------------------------------------------------------------- rooms
    op.create_table(
        "rooms",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("colour_var", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("name", name=op.f("uq_rooms_name")),
    )

    # ------------------------------------------------------------------ holidays
    # Seeded by nobody. Reception and admin maintain this table, and
    # scripts/load_holidays.py imports a CSV of date,name. The Sunday closure is
    # computed from settings.closed_weekdays and is never stored as rows here.
    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("date", name=op.f("uq_holidays_date")),
    )

    # --------------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("role", user_role, nullable=False, server_default="EMPLOYEE"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_users_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )

    # ------------------------------------------------------------------ bookings
    op.create_table(
        "bookings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("room_id", sa.String(length=16), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("conducted_by", sa.Integer(), nullable=False),
        sa.Column("booked_by", sa.Integer(), nullable=False),
        sa.Column(
            "title", sa.String(length=120), nullable=False, server_default="Meeting"
        ),
        sa.Column("reception_note", sa.Text(), nullable=True),
        sa.Column(
            "status", booking_status, nullable=False, server_default="CONFIRMED"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "exit_time > entry_time", name=op.f("ck_bookings_exit_after_entry")
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_bookings_room_id_rooms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_bookings_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conducted_by"],
            ["users.id"],
            name=op.f("fk_bookings_conducted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["booked_by"],
            ["users.id"],
            name=op.f("fk_bookings_booked_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.create_index(
        "ix_bookings_room_id_booking_date", "bookings", ["room_id", "booking_date"]
    )
    op.create_index(
        "ix_bookings_booking_date_status", "bookings", ["booking_date", "status"]
    )
    op.create_index("ix_bookings_entry_time", "bookings", ["entry_time"])

    # ---------------------------------------------------------- booking_attendees
    op.create_table(
        "booking_attendees",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("booking_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "response_status",
            attendee_response,
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_attendees_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_booking_attendees_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_attendees")),
        sa.UniqueConstraint(
            "booking_id", "user_id", name="uq_booking_attendees_booking_id_user_id"
        ),
    )
    op.create_index("ix_booking_attendees_user_id", "booking_attendees", ["user_id"])

    # ----------------------------------------------------------- notification_log
    op.create_table(
        "notification_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("booking_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("event", notification_event, nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", notification_status, nullable=False, server_default="QUEUED"
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_notification_log_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_log")),
    )
    op.create_index(
        "ix_notification_log_booking_id", "notification_log", ["booking_id"]
    )

    # ------------------------------------------------------------------ audit_log
    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_entity_entity_id", "audit_log", ["entity", "entity_id"])

    # ---------------------------------------------- layer 3: the real guarantee
    # Spec section 7, reproduced exactly. The '[)' bound is what makes a booking
    # that ends at 15:00 and one that starts at 15:00 back to back rather than a
    # clash. The WHERE clause scopes it to CONFIRMED, so cancelling a booking or
    # marking it NO_SHOW releases the room the instant it happens.
    #
    # Guarded so that a re-run after a partly applied migration adds it once and
    # does not abort on "constraint already exists".
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'no_double_booking'
            ) THEN
                ALTER TABLE bookings
                ADD CONSTRAINT no_double_booking
                EXCLUDE USING gist (
                    room_id WITH =,
                    tstzrange(entry_time, exit_time, '[)') WITH &&
                ) WHERE (status = 'CONFIRMED');
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE bookings DROP CONSTRAINT IF EXISTS no_double_booking;")

    op.drop_index("ix_audit_log_entity_entity_id", table_name="audit_log")
    op.drop_table("audit_log")

    op.drop_index("ix_notification_log_booking_id", table_name="notification_log")
    op.drop_table("notification_log")

    op.drop_index("ix_booking_attendees_user_id", table_name="booking_attendees")
    op.drop_table("booking_attendees")

    op.drop_index("ix_bookings_entry_time", table_name="bookings")
    op.drop_index("ix_bookings_booking_date_status", table_name="bookings")
    op.drop_index("ix_bookings_room_id_booking_date", table_name="bookings")
    op.drop_table("bookings")

    op.drop_table("users")
    op.drop_table("holidays")
    op.drop_table("rooms")
    op.drop_table("departments")

    op.execute("DROP TYPE IF EXISTS notification_status;")
    op.execute("DROP TYPE IF EXISTS notification_event;")
    op.execute("DROP TYPE IF EXISTS attendee_response;")
    op.execute("DROP TYPE IF EXISTS booking_status;")
    op.execute("DROP TYPE IF EXISTS user_role;")

    # btree_gist is deliberately left installed. Dropping an extension is a
    # database-wide act and nothing else in this migration created the database.
